---

date: 2019-12-19T15:52:19+0800

---

recover 只能从 defer 中恢复? 如果是正常调用一个函数, 里面 panic 了, 我想 try/catch 怎么办?
